/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package checkout;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Suvier
 */
public class SelectExtension extends javax.swing.JFrame {

    /**
     * Creates new form SelectExtension
     */
    public SelectExtension() {
        initComponents();
    }
    
    public int calculateNewCheckoutDate(int currentCheckoutDate, int extensionDays) {
        int year = currentCheckoutDate / 10000;
        int month = (currentCheckoutDate / 100) % 100;
        int day = currentCheckoutDate % 100;
        
        day += extensionDays;
        
        if (day > 30) {
            month += day / 30;
            day = day % 30;
        }
        if (month > 12) {
            year += month / 12;
            month = month % 12;
        }
        return year * 10000 + month * 100 + day;
    }
    
    public boolean isRoomAvailabe(int newCheckoutDate, String roomNumber, List<ClientInfo> allClients) {
        for (ClientInfo client : allClients) {
            if (client.roomNumber.equal(roomNumber) && client.checkInDate <= newCheckoutDate) {
                return false;
            }
        }
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExtensionDay = new javax.swing.JLabel();
        ExtensionDate = new javax.swing.JTextField();
        OKButton = new javax.swing.JButton();
        Date = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ExtensionDay.setText("연장 일수를 입력해주세요. :");

        ExtensionDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtensionDateActionPerformed(evt);
            }
        });

        OKButton.setText("확인");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        Date.setText("일");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(ExtensionDay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExtensionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(OKButton)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExtensionDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExtensionDay)
                    .addComponent(Date))
                .addGap(18, 18, 18)
                .addComponent(OKButton)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        OKButton.addActionListener(e -> {
            int extensionDays = Integer.parseInt(ExtensionDate.getText().trim());
            ClientInfo selectedClient = this.selectedClient;
            int newCheckoutDate = calculateNewCheckoutDate(selectedClient.checkoutDate, extensionDays);
            List<ClientInfo> allClients = FileRead.readClientData("clientInfo1.txt");
            boolean roomAvailable = isRoomAvailable(newCheckoutDate, selectedClient.roomNumber, allClients);

            if (roomAvailable) {
                HaveRoom haveRoom = new HaveRoom(newCheckoutDate, selectedClient);
                haveRoom.setVisible(true);
                this.dispose();
            }
            else {
                NoRoom noRoom = new NoRoom();
                noRoom.setVisible(true);
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExtensionDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtensionDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExtensionDateActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OKButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Date;
    private javax.swing.JTextField ExtensionDate;
    private javax.swing.JLabel ExtensionDay;
    private javax.swing.JButton OKButton;
    // End of variables declaration//GEN-END:variables
}
